import streamlit as st
import io, fitz, pdfplumber, re, pandas as pd, numpy as np
import torch
from PIL import Image
from torchvision import models, transforms
from sklearn.metrics.pairwise import cosine_similarity
from supabase import create_client, Client

# ================= CONFIG =================
URL= "https://ewqqodsfvlvnrzsylawy.supabase.co"
KEY = "sb_publishable_yxioECJT07sMQWL_rtSyFg_vJ1DF2ri"
BUCKET = "fashion-imgs"

supabase: Client = create_client(URL, KEY)

st.set_page_config(layout="wide", page_title="AI Fashion Pro V47", page_icon="📊")

# ================= AUTO INIT DB =================
def init_db():
    try:
        supabase.rpc("exec_sql", {
            "sql": """
            create table if not exists ai_data (
                id bigint generated by default as identity primary key,
                file_name text,
                vector float8[],
                spec_json jsonb,
                image_url text,
                category text,
                created_at timestamp default now()
            );
            """
        }).execute()
    except:
        pass

init_db()

# ================= SESSION =================
if "up_key" not in st.session_state: st.session_state.up_key = 0
if "au_key" not in st.session_state: st.session_state.au_key = 0

# ================= LOAD AI =================
@st.cache_resource
def load_ai():
    try:
        model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
        return torch.nn.Sequential(*(list(model.children())[:-1])).eval()
    except:
        return None

model_ai = load_ai()

# ================= PARSE =================
def parse_val(t):
    try:
        if t is None: return 0
        txt = str(t).replace(',', '.').strip().lower()
        if not txt or any(x in txt for x in ['nan', '-', 'none', 'tol']): return 0
        match = re.findall(r'(\d+\s\d+/\d+|\d+/\d+|\d+\.\d+|\d+)', txt)
        if not match: return 0
        v = match[0]
        if ' ' in v:
            p = v.split()
            return float(p[0]) + eval(p[1])
        return eval(v) if '/' in v else float(v)
    except:
        return 0

def clean_pos(t):
    return re.sub(r'[^A-Z0-9]', '', str(t).upper())

# ================= EXTRACT =================
def extract_pom(pdf_file):
    full_specs, img_bytes, brand = {}, None, "OTHER"
    try:
        pdf_content = pdf_file.read()

        doc = fitz.open(stream=pdf_content, filetype="pdf")
        if len(doc) > 0:
            img_bytes = doc.load_page(0).get_pixmap().tobytes("png")

        text_all = ""
        for p in doc:
            text_all += (p.get_text() or "").upper()

        if "REITMANS" in text_all:
            brand = "REITMANS"

        doc.close()

        with pdfplumber.open(io.BytesIO(pdf_content)) as pdf:
            for page in pdf.pages:
                if any(x in (page.extract_text() or "") for x in ["THREAD", "BUTTON"]):
                    continue

                tables = page.extract_tables()
                for tb in tables:
                    df = pd.DataFrame(tb).dropna(how='all', axis=1)
                    if df.empty or len(df.columns) < 2:
                        continue

                    for i in range(len(df)):
                        name = str(df.iloc[i][0]).upper()
                        val = parse_val(df.iloc[i][1])
                        if val > 0:
                            full_specs[name] = val

        return {"specs": full_specs, "img": img_bytes, "brand": brand}
    except:
        return None

# ================= SIDEBAR =================
with st.sidebar:
    st.header("📂 KHO DỮ LIỆU")

    try:
        res = supabase.table("ai_data").select("*", count="exact").execute()
        st.metric("Đã nạp", res.count)
    except Exception as e:
        st.error(f"Lỗi DB: {e}")

    files = st.file_uploader("Upload Techpack", accept_multiple_files=True)

    if files and st.button("🚀 NẠP"):
        for f in files:
            d = extract_pom(f)

            if not d or not d['specs']:
                st.warning(f"Lỗi đọc: {f.name}")
                continue

            img_url = ""
            vec = []

            try:
                if d['img']:
                    path = f"lib/{f.name}.png"

                    supabase.storage.from_(BUCKET).upload(
                        path,
                        d['img'],
                        {"upsert": "true"}
                    )

                    pub = supabase.storage.from_(BUCKET).get_public_url(path)
                    img_url = pub.get("publicUrl", "")

                if model_ai and d['img']:
                    img = Image.open(io.BytesIO(d['img'])).convert("RGB")

                    tf = transforms.Compose([
                        transforms.Resize((224, 224)),
                        transforms.ToTensor()
                    ])

                    with torch.no_grad():
                        vec = model_ai(tf(img).unsqueeze(0)).flatten().numpy().tolist()

            except Exception as e:
                st.warning(f"Lỗi ảnh: {e}")

            try:
                supabase.table("ai_data").insert({
                    "file_name": f.name,
                    "vector": vec,
                    "spec_json": d['specs'],
                    "image_url": img_url,
                    "category": d['brand']
                }).execute()

                st.success(f"✅ {f.name}")

            except Exception as e:
                st.error(f"Lỗi insert: {e}")

        st.rerun()

# ================= MAIN =================
st.title("🔍 AI Auditor V47")

t_file = st.file_uploader("Upload file kiểm", type="pdf")

if t_file:
    target = extract_pom(t_file)

    if target and target['specs']:
        st.success(f"Tìm thấy {len(target['specs'])} POM")

        db = supabase.table("ai_data").select("*").execute()

        if db.data:
            matches = []

            v_test = None
            if target['img'] and model_ai:
                img = Image.open(io.BytesIO(target['img'])).convert("RGB")
                tf = transforms.Compose([
                    transforms.Resize((224, 224)),
                    transforms.ToTensor()
                ])
                with torch.no_grad():
                    v_test = model_ai(tf(img).unsqueeze(0)).flatten().numpy().reshape(1, -1)

            for row in db.data:
                sim = 0
                if v_test is not None and row.get("vector"):
                    v_ref = np.array(row["vector"]).reshape(1, -1)
                    sim = float(cosine_similarity(v_test, v_ref)[0][0]) * 100

                matches.append({"data": row, "sim": sim})

            top = sorted(matches, key=lambda x: x['sim'], reverse=True)[:1]

            for m in top:
                st.subheader(f"Best match: {m['data']['file_name']} ({m['sim']:.1f}%)")

                c1, c2 = st.columns(2)

                if target['img']:
                    with c1:
                        st.image(target['img'])

                if m['data'].get("image_url"):
                    with c2:
                        st.image(m['data']['image_url'])

                diff = []
                for k, v in target['specs'].items():
                    ref = m['data']['spec_json'].get(k, 0)
                    diff.append([k, v, ref, round(v-ref,2)])

                df = pd.DataFrame(diff, columns=["POM","NEW","REF","DIFF"])
                st.dataframe(df)

# ================= RESET =================
if st.button("🗑️ Reset"):
    st.session_state.au_key += 1
    st.rerun()
